FROM node:latest AS development

WORKDIR /chat/frontend/src/app

COPY package*.json ./

RUN npm install
RUN npm install -g @angular/cli@12.0.0


COPY . .

RUN npm run build

EXPOSE 4200

#npm i --save @nestjs/config 
#npm i --save @nestjs/typeorm typeorm pg 